// Sample app strings for the design-system tests, in English and Arabic.
//
// The design system never translates app strings: components take
// already-localized text. Before the extraction (step 2.11) the tests called
// the app's translator for these sample labels. The package can't depend on
// the app, so the Arabic text the app produced for each sample label is
// copied here verbatim. That keeps every golden byte-identical. English
// labels are the keys themselves (the app's `en` table doesn't change them).
//
// These are synthetic UI labels only; no patient or staff data.
const Map<String, String> sampleArabicStrings = {
  '2- Select Ambulance': '2- اختر سيارة الإسعاف',
  'Advanced': 'متقدم',
  'Alert': 'تنبيه',
  'Back': 'رجوع',
  'Basic': 'أساسي',
  'COPD': 'الانسداد الرئوي المزمن',
  'Cancel': 'إلغاء',
  'Cancelled': 'ملغي',
  'Case & Insurance': 'الحالة والتأمين',
  'Clinical Assessment': 'التقييم السريري',
  'Clinical Assessment Details': 'تفاصيل التقييم السريري',
  'Completed': 'مكتمل',
  'Dark Mode': 'الوضع الداكن',
  'Dashboard': 'لوحة التحكم',
  'Dispatch': 'إرسال',
  'Done': 'مكتمل',
  'Dose': 'الجرعة',
  'Driver': 'سائق',
  'During Handover =2': 'أثناء التسليم =2',
  'During transport =1': 'أثناء النقل =1',
  'EMT': 'فني طوارئ طبية',
  'Email': 'البريد الإلكتروني',
  'Enter notes...': 'أدخل الملاحظات...',
  'Equipment': 'المعدات',
  'Eyes Open (E)': 'فتح العينين (E)',
  'Finish': 'إنهاء',
  'Follow Trip': 'متابعة الرحلة',
  'Handover & Closure': 'التسليم والإغلاق',
  'In Progress': 'قيد التنفيذ',
  'InProgress': 'قيد التنفيذ',
  'Inspected': 'تم الفحص',
  'LifeThreatening': 'مهدد للحياة',
  'Loading...': 'جاري التحميل...',
  'Location': 'الموقع',
  'Medical Intervention': 'التدخل الطبي',
  'Medication Name': 'اسم الدواء',
  'Motor Response (M)': 'الاستجابة الحركية (M)',
  'NONE': 'لا شيء',
  'National ID': 'الهوية الوطنية',
  'Next': 'التالي',
  'Night shift handover starts in 20 minutes.':
      'يبدأ تسليم مناوبة الليل خلال 20 دقيقة.',
  'NonUrgent': 'غير طارئ',
  'Notes': 'ملاحظات',
  'Notification Alert:': 'تنبيه إشعار:',
  'Notifications': 'الإشعارات',
  'Open': 'مفتوح',
  'Pain': 'استجابة للألم',
  'Paramedic': 'مسعف',
  'Password': 'كلمة المرور',
  'Patient Name': 'اسم المريض',
  'Precaution Notes': 'ملاحظات الاحتياطات',
  'Pulse': 'النبض',
  'Readiness Overview': 'نظرة عامة على الجاهزية',
  'Ready': 'جاهز',
  'Ready State': 'حالة الجاهزية',
  'RecordedAt': 'وقت التسجيل',
  'Report': 'تقرير',
  'Route': 'طريقة الإعطاء',
  'SBAR & Staff': 'SBAR والطاقم',
  'SPO2': 'تشبع الأكسجين',
  'SPONTANEOUS': 'تلقائي',
  'Search Medication': 'البحث عن دواء',
  'Select Crew': 'اختر الطاقم',
  'Select date and time...': 'اختر التاريخ والوقت...',
  'Settings': 'الإعدادات',
  'Sign In': 'تسجيل الدخول',
  'Sign Out': 'تسجيل الخروج',
  'Status': 'الحالة',
  'Stroke': 'السكتة الدماغية',
  'Supervisor': 'مشرف',
  'Temperature': 'الحرارة',
  'This field is required': 'هذا الحقل مطلوب',
  'Unresponsive': 'غير مستجيب',
  'Urgent': 'طارئ',
  'Vehicle': 'المركبة',
  'Verbal': 'استجابة لفظية',
  'Vital Signs': 'العلامات الحيوية',
  'or': 'أو',
};
